# Generated by Django 2.0 on 2018-04-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dropbox_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user_id',
            new_name='username',
        ),
    ]
